[settings]
idiomatic_version_file_enable_tools = ["node"]

[tools]
aws = { version = "latest", symlink_bins = "true" }
gcloud = "latest"
node = "24"
ripgrep = "latest"
usage = "latest"
yarn = "latest"
fzf = "latest"
fd = "latest"
bat = "latest"
java = "zulu-17"
go = "latest"
rust = "latest"
bun = "latest"
gh = "latest"
jfrog-cli = "latest"
supabase = "latest"
vercel = "latest"
neovim = "latest"
starship = "latest"
zoxide = "latest"
